#+STARTUP: show2levels
* Freebsd Cuda
** Project overview

Run Linux command line and gui applications on FreeBSD with full Nvidia Cuda hardware acceleration.

🎥 [[https://www.youtube.com/watch?v=Txq8tXH9Wow][Cuda working on Freebsd using Podman containers]]

Mounts the Linuxulator libraries from Freebsd into the Podman containers,
so you dont need to install the Nvidia driver into the container.

Wayland/X11 and PulseAudio Pass-through.

Displays graphics and routes audio via native FreeBSD sockets mounted inside the Podman container.

Hardware acclerated video.

Persistent storage for files so settings are retained when stopping containers.

Directory mounted from Freebsd into the Podman container for file access.

GUI Applications launched with desktop entries on Freebsd.

*** Pre-configured Applications
**** Davinci Resolve with Cuda

[[https://www.blackmagicdesign.com/uk/products/davinciresolve]]

**** Firefox with hardware accelerated video and Widevine DRM support.

[[https://www.firefox.com/en-GB/]]

**** ffmpeg with hardware-accelerated nvenc encoding.

[[https://www.ffmpeg.org/]]

**** ComfYU

[[https://github.com/comfy-org/comfyui]]

**** demucs audio separation with cuda support

[[https://github.com/adefossez/demucs]]

**** kokoro-onnx using Cuda.

[[https://github.com/thewh1teagle/kokoro-onnx]]

**** WhisperX audio transcription with Cuda acceleration.

[[https://github.com/m-bain/whisperX]]

**** Ollama using Cuda.

[[https://github.com/ollama/ollama]]

**** Blender

[[https://www.blender.org/]]

** Inital set up
*** Follow the podman install instructions

Follow the podman install instruction to get podman working.

Once you have the hello world container working you can proceed with the installation.

*** Clone the git repository

The podman set up instructions will set up a zfs dataset which is mounted at ~/podman.

Change into the podman directory.

#+begin_src sh
cd ~/podman
#+end_src

Clone the git repository.

#+begin_src sh
git clone https://github.com/NapoleonWils0n/freebsd-cuda.git
#+end_src

*** Required packages for audio

You need pipewire, pulseaudio and pavucontrol installed.

#+begin_src sh
doas pkg install pipewire pulseaudio pavucontrol
#+end_src

*** Pulseaudio config
**** Option one use the Makefile

#+begin_src sh
cd ~/podman/freebsd-cuda/base-build/pulseaudio
#+end_src

run the Makefile to create the directory and file.

#+begin_src sh
make
#+end_src

**** Option two manually create the directory and file

Create the pulseaudio directory.

#+begin_src sh
mkdir -p ~/.config/pulse
#+end_src

Create the default.pa file.

#+begin_src sh
vi ~/.config/pulse/default.pa
#+end_src

Add the following code.

#+begin_src conf
#!/usr/local/bin/pulseaudio -nF

# include default.pa and override
.include /usr/local/etc/pulse/default.pa

# pulseaudio.socket
.ifexists module-esound-protocol-unix.so
load-module module-esound-protocol-unix
.endif
load-module module-native-protocol-unix socket=/tmp/pulseaudio.socket
#+end_src

*** wrapper-freebsd

The wrapper-freebsd script is used to launch gui application and works with the wrapper-podman script which is installed in the podman containers and a desktop entry.

Copy the wrapper-freebsd script to your bin directory.

If you have a bin directory in your home.

#+begin_src sh
cp ~/podman/freebsd-cuda/base-build/assets/scripts/wrappers/wrapper-freebsd ~/bin
#+end_src

If you dont have a bin directory in your home you can copy the script to.

#+begin_example
/usr/local/bin
#+end_example

#+begin_src sh
doas cp ~/podman/freebsd-cuda/base-build/assets/scripts/wrappers/wrapper-freebsd /usr/local/bin
#+end_src

** Build the images
*** base-image
**** Change into the base-image directory
***** Wayland

If you are using Wayland change into the wayland directory.

And then follow the Build the base-image instructions.

#+begin_src sh
cd ~/podman/freebsd-cuda/base-build/base-image/wayland
#+end_src

***** X11

If you are using X11 change into the x11 directory.

And then follow the Build the base-image instructions.

#+begin_src sh
cd ~/podman/freebsd-cuda/base-build/base-image/x11
#+end_src

**** Build the base-image

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_UID="$(id -u)" \
--build-arg HOST_USER="${USER}" \
-t localhost/base-image .
#+end_src

**** dummy-uvm.so

Note you dont need to build the dummy-uvm its included in the project.

These are just project notes on building the dummy-uvm.

Change into the uvm_ioctl_override directory.

#+begin_src sh
cd ~/podman/freebsd-cuda/base-build/uvm_ioctl_override
#+end_src

Build the dummy-uvm.so with the podman container.

#+begin_src sh
doas podman run --network host --rm -it --os linux -v .:/build:z docker.io/library/rockylinux:9.3 /bin/bash -c "dnf install -y gcc && gcc -m64 -std=c99 -O2 -fPIC -shared -o /build/dummy-uvm.so /build/uvm_ioctl_override.c -ldl"
#+end_src

Change the permissions on the dummy-uvm.so file.

#+begin_src sh
doas chown root:wheel dummy-uvm.so
doas chmod 755 dummy-uvm.so
#+end_src

Remove the old dummy-uvm.so.

#+begin_src sh
rm -i ~/podman/freebsd-cuda/base-build/dummy-uvm/dummy-uvm.so
#+end_src

Move the new dummy-uvm.so into the dummy-uvm directory.

#+begin_src sh
mv dummy-uvm.so ../dummy-uvm/
#+end_src

*** ai
**** ollama
***** Create the Ollama directory

Create a zfs dataset for Ollama,

change djwilcox to your username in the code below.

#+begin_src sh
doas zfs create zroot/home/djwilcox/.ollama
#+end_src

Then change the permissions.

#+begin_src sh
doas chown -R djwilcox:djwilcox /home/djwilcox/.ollama
#+end_src

If you dont use zfs you can just create a directory.

#+begin_src sh
mkdir -p ~/.ollama
#+end_src

***** Change directory into the ollama directory

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/ai/ollama
#+end_src

***** Run the Makefile

Run make Makefile.

And the .env file which will set your username, id and set the mounted Downloads directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

***** Build the ollama container

Note change the OLLAMA_VERSION="v0.33.3" to the latest version.

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_USER="${USER}" \
--build-arg OLLAMA_VERSION="v0.33.3" \
-t localhost/ollama .
#+end_src

***** View the logs

You need to view logs and wait for install to finish.

#+begin_src sh
doas podman-compose logs -f
#+end_src

ctrl c to exit logs.

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** Enter the container

#+begin_src sh
doas podman exec -it -u ${USER} ollama /bin/bash
#+end_src

***** ollama serve

Run Ollama

#+begin_src sh
ollama serve
#+end_src

For older Turing Nvidia Gpu's like my GeForce GTX 1650,

You need to use the following code to use cuda_v12.

#+begin_src sh
OLLAMA_LLM_LIBRARY=cuda_v12 ollama serve
#+end_src

***** Exit the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

***** Makefile

To make starting easier i created a Makefile you can use to start and stop Ollama.

1) Copy the wrapper-freebsd script to your bin directory as explained earlier.

2) Create a directory for the Makefile

#+begin_src sh
mkdir -p ~/make/ollama
#+end_src

3) Copy the Makefile into the directory.

#+begin_src sh
cp ~/podman/freebsd-cuda/base-build/assets/makefiles/ollama/Makefile ~/make/ollama
#+end_src

4) Using the Makefile

Change into the directory with the Ollama Makefile.

#+begin_src sh
cd ~/make/ollama
#+end_src

Start Ollama

#+begin_src sh
make
#+end_src

Stop Ollama

#+begin_src sh
make clean
#+end_src
   
*** Scripts
**** ffmpeg scripts

🎥 [[https://www.youtube.com/watch?v=yDMtzK4ZkkQ][ffmpeg nvenc encoding working in a Linux Podman container on Freebsd]]

***** Change directory into the ffmpeg directory

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/scripts/ffmpeg
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Downloads directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

***** pulseaudio

If you want to use ffplay,

Open pulseaudio volume control on the Freebsd host to start pulseaudio.

Keep pulseaudio volume control open.

This will create the pulseaudio.socket and keep the socket open.

***** Build the ffmpeg container

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_USER="${USER}" \
-t localhost/ffmpeg-scripts .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** View the logs

You need to view logs and wait for install to finish.

#+begin_src sh
doas podman-compose logs -f
#+end_src

ctrl c to exit.

***** Enter the container

#+begin_src sh
doas podman exec -it -u ${USER} ffmpeg-scripts /bin/bash
#+end_src

Change into the ~/video directory in the container.

#+begin_src sh
cd ~/video
#+end_src

Copy a file to process from the freebsd host into the mountpoint.

Then in the container you will have access to the same file.

note:

To view the yt-dlp help run pipe it into less.

#+begin_src sh
yt-dlp -h | less
#+end_src

Otherwise it causes issue and the container will exit.

***** Exit the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

*** Browsers
**** Firefox

🎥 [[https://www.youtube.com/watch?v=EG3s5vKM3fs][Freebsd Firefox Widevine for DRM playback in Rocky Linux Podman container]]

***** Change directory into the firefox directory

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/browsers/firefox
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Downloads directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

***** Build the firefox container

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_USER="${USER}" \
-t localhost/firefox .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** Enter container

#+begin_src sh
doas podman exec -it -u ${USER} firefox /bin/bash
#+end_src

***** Widevine set up

Open the setting from the hamburger menu,

Or use the following url.

#+begin_example
about:settings
#+end_example

In the general settings section,

Check the box to playback drm in the firefox settings.

Next open about:profiles in the url bar.

#+begin_example
about:profiles
#+end_example

make a note of your profile.

close firefox.

copy the user.js file into the profile directory.

Check your profile before copying the file.

Example command you must change s2vvkzgl.default-default to your profile.

#+begin_src sh
cp ~/podman/freebsd-cuda/base-build/assets/applications/firefox/user.js ~/podman/freebsd-cuda/containers/browsers/firefox/dotfiles/mozilla/firefox/s2vvkzgl.default-default/
#+end_src

***** exit the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

***** freebsd-podman.desktop

Copy the freebsd-podman.desktop file into

#+begin_example
~/.local/share/applications
#+end_example

#+begin_src sh
cp ~/podman/freebsd-cuda/base-build/assets/applications/firefox/firefox-podman.desktop ~/.local/share/applications
#+end_src

***** Stop the container

Change into the container directory.

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/browsers/firefox
#+end_src

And stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

*** Python
**** comfyui

🎥 [[https://www.youtube.com/watch?v=DfG4pOf0EiQ][ComfyUI with Cuda on Freebsd]]

***** Change directory into the comfyui directory

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/python/comfyui
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Videos directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

Note: You may need to change medvram to either lowvram or highvram depending on your set up.

#+begin_example
HOST_COMMANDLINE_ARGS="--xformers --disable-dynamic-vram --medvram"
#+end_example

***** comfy_aimdo fix

You need to edit the comfy_aimdo/control.py file and comment out some code,
and add a small block of code.

#+begin_src sh
vi ComfyUI/.venv/lib/python3.12/site-packages/comfy_aimdo/control.py
#+end_src

Comment out the code as shown below, and add the new code block at the top.

#+begin_src python
def init_devices(device_ids):
    return False

#def init_devices(device_ids):
#    global devctxs
#
#    if lib is None:
#        return False
#
#    requested = [int(device_id) for device_id in device_ids]
#    if not requested:
#        return False
#
#    if not lib.plat_init():
#        return False
#
#    device_array = (ctypes.c_int * len(requested))(*requested)
#    if lib.init(device_array, len(requested)):
#        devctxs = [get_devctx(device_id) for device_id in requested]
#        return True
#
#    devctxs = []
#    lib.plat_cleanup()
#    return False
#+end_src

***** build

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_USER="${USER}" \
-t localhost/comfyui .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** View the logs

You need to view logs and wait for install to finish.

#+begin_src sh
doas podman-compose logs -f
#+end_src

ctrl c to exit logs.

***** Enter container

#+begin_src sh
doas podman exec -it -u ${USER} comfyui /bin/bash
#+end_src

***** webui

Change into the ComfyUI directory.

#+begin_src sh
cd ComfyUI
#+end_src

Start the webui.

#+begin_src sh
python main.py
#+end_src

Open the webui.

[[http://127.0.0.1:8188]]

***** Downloading models

Move download models to

#+begin_example
ComfyUI/models/checkpoints
#+end_example

***** Stop the container

Change into the container directory.

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/python/comfyui
#+end_src

And stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

**** demucs
***** Change directory into the demucs directory

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/python/demucs
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Videos directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

***** Build the container

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_USER="${USER}" \
-t localhost/demucs .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** View the logs

You need to view logs and wait for install to finish.

#+begin_src sh
doas podman-compose logs -f
#+end_src

ctrl c to exit logs.

***** Enter container

#+begin_src sh
doas podman exec -it -u ${USER} demucs /bin/bash
#+end_src

***** run demucs

change into the video directory mounted from Freebsd.

#+begin_src sh
cd ~/video
#+end_src

extract audio from a video file,
or process an existing audio file

#+begin_src sh
ffmpeg -i input.mp4 -vn -c:a pcm_s16le input.wav
#+end_src

run demucs to separate the audio into vocals and music.

the first time you run the command it will download the model.

#+begin_src sh
demucs -d cuda --float32 --two-stems=vocals -n htdemucs_ft input.wav
#+end_src

***** Exit the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

**** kokoro

🎥 [[https://www.youtube.com/watch?v=iUrTC4PrBpM][Kokoro-onnx with Cuda for text to speech with Emacs]]

***** resources

kokoro-onnx tts with Cuda support.

[[https://github.com/thewh1teagle/kokoro-onnx]]

***** Change directory into the kokoro-onnx directory

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/python/kokoro-onnx
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Videos directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

***** Build the container

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_USER="${USER}" \
-t localhost/kokoro-onnx .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** View the logs

You need to view logs and wait for install to finish.

#+begin_src sh
doas podman-compose logs -f
#+end_src

ctrl c to exit logs.

***** Enter container

#+begin_src sh
doas podman exec -it -u ${USER} kokoro-onnx /bin/bash
#+end_src

***** kokoro scripts
****** curl

#+begin_src sh
curl -X POST "http://127.0.0.1:8000/v1/audio/speech" \
     -H "Content-Type: application/json" \
     -d '{"text": "Kokoro onnx text to speech using curl.", "voice": "bm_lewis"}'
#+end_src

****** kokoro

The container will automatically mount your video directory from Freebsd.

Inside the container you can change directory into the mounted directory to process the text file and save the output.

Run the kokoro script with the -h option to show the help.

#+begin_src sh
kokoro -h
#+end_src

Help output.

#+begin_example
Usage: kokoro -f <input_text_file> [OPTIONS]

Options:
  -f <file>    Path to the input text file to read from (Required)
  -o <file>    Path to the output wav file destination
               Default: input-filename.wav
  -v <voice>   Specify the speaker voice variant
               Default: bm_lewis
  -h           Display this help usage screen

Available Voices Reference:
  https://huggingface.co/hexgrad/Kokoro-82M/blob/main/VOICES.md
#+end_example

Run the kokoro script.

#+begin_src sh
kokoro -f input.txt 
#+end_src

Use the -f option with a text file to process.

Use the -v option to specify a voice.

[[https://huggingface.co/hexgrad/Kokoro-82M/blob/main/VOICES.md]]

If you omit the -f option the default voice bm_lewis will be used.

Use the -o option to specify an output filename.

If you omit the -o option the default ouput filename will be the name of input file with a .wav extension.

****** kokoro-api

The kokoro-api script allows you to read text from Freebsd,
using either emacs or the kokoro-read script which accepts a file or from text on the clipboard.

Copy the kokoro script to your home bin directory 

#+begin_src sh
cp ~/podman/freebsd-cuda/base-build/assets/scripts/kokoro/* ~/bin
#+end_src

If you dont have a bin directory in your home copy them /usr/local/bin

#+begin_src sh
doas cp ~/podman/freebsd-cuda/base-build/assets/scripts/kokoro/* /usr/local/bin
#+end_src

******* kokoro-start

The kokoro-start script starts the kokoro-onnx podman container and the kokoro-api script.

You need to open pulseaudio volume control on the Freebsd host to start pulseaudio,
before running the kokoro-start script.

Keep pulseaudio volume control open.

This will create the pulseaudio.socket and keep the socket open.

Run the kokoro-start script.

#+begin_src sh
kokoro-start
#+end_src

******* kokoro-read

Open pulse audio volume control and run the kokoro-start script.

The kokoro-read script accepts a file or from text on the clipboard.

Run the kokoro-read with the -h option to display the help.

#+begin_src sh
kokoro-read -h
#+end_src

Help output.

#+begin_example
kokoro-read -i input -c on -v voice
-i : accepts a text file
-c on : reads the contents of the clipboard
-v voice : specify the voice to use
#+end_example

To read text from the clipboard run.

#+begin_src sh
kokoro-read -c on
#+end_src

Note the clipboard function use the wayland clipboard,
if you use X11 edit the clipboard function and change the following code.

#+begin_example
"$(wl-paste | tr -d '\n')"
#+end_example

To

#+begin_example
"$(xclip -o | tr -d '\n')"
#+end_example

******* emacs kokoro-speak-region

After opening pulseaudio volume control and running the kokoro-start script,
and adding the following code to your emacs init.el.

You can select a region of text and run the keyboard shortcut to read the text.

#+begin_example
C-c s
#+end_example

Edit your emacsd init.el

#+begin_example
~/.config/emacs/init.el
#+end_example

Add the following code.

#+begin_src emacs-lisp
;; ----------------------------------------------------------------------------------
;; kokoro speak region
;; ----------------------------------------------------------------------------------

(require 'json)
(defun my/kokoro-speak-region (start end)
  "Send the selected region to the Kokoro API."
  (interactive "r")
  (let* ((text (buffer-substring-no-properties start end))
         (payload (json-encode `(("text" . ,text) ("voice" . "bm_lewis")))))
    (start-process "kokoro-curl-process" nil 
                   "curl" "-s" "-X" "POST" "http://127.0.0.1:8000/v1/audio/speech"
                   "-H" "Content-Type: application/json"
                   "-d" payload)))

(global-set-key (kbd "C-c s") 'my/kokoro-speak-region)
#+end_src

***** Exit the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

***** Makefile

To make starting easier i created a Makefile you can use to start and stop kokoro-onnx

1) Copy the wrapper-freebsd script to your bin directory as explained earlier.

2) Create a directory for the Makefile

#+begin_src sh
mkdir -p ~/make/kokoro
#+end_src

3) Copy the Makefile into the directory.

#+begin_src sh
cp ~/podman/freebsd-cuda/base-build/assets/makefiles/kokoro/Makefile ~/make/kokoro
#+end_src

4) Using the Makefile

Change into the directory with the Ollama Makefile.

#+begin_src sh
cd ~/make/kokoro
#+end_src

Start kokoro

#+begin_src sh
make
#+end_src

Stop kokoro

#+begin_src sh
make clean
#+end_src
   
**** whisperx
***** Change directory into the whisperx directory

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/python/whisperx
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Videos directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

***** Add your huggingface token to the file

Sign up for huggingface and create a access token.

[[https://huggingface.co]]

You then need to go the the speaker diarization url.

Fill out the quick agreement form and click Accept / Request Access.

[[https://huggingface.co/pyannote/speaker-diarization-community-1]]

#+begin_src sh
vi dotfiles/cache/huggingface/token
#+end_src

***** Build the container

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_USER="${USER}" \
-t localhost/whisperx .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** View the logs

You need to view logs and wait for install to finish.

#+begin_src sh
doas podman-compose logs -f
#+end_src

ctrl c to exit logs.

***** Enter container

#+begin_src sh
doas podman exec -it -u ${USER} whisperx /bin/bash
#+end_src

***** Run the python check for cuda

#+begin_src python
python3 -c "import torch; print('CUDA Available:', torch.cuda.is_available()); print('Device:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'None')"
#+end_src

the output should look similar to this and list your Nvidia card.

#+begin_example
CUDA Available: True
Device: NVIDIA GeForce GTX 1650
#+end_example

***** Small model download

Change directory in to the ~/video directory in the container.

Download the small model.

In this example using a audio file called input.wav.

#+begin_src sh
whisperx input.wav \
--device cuda \
--model small \
--diarize \
--highlight_words True \
--language en \
--compute_type float32
#+end_src

***** Medium model download

Change directory in to the ~/video directory in the container.

Download the medium model.

In this example using a audio file called input.wav.

#+begin_src sh
whisperx input.wav \
--device cuda \
--model medium \
--compute_type int8 \
--batch_size 4 \
--threads 1 \
--diarize \
--highlight_words True \
--language en
#+end_src

***** Exit the container

When you have finished you can exit the container.

#+begin_src sh
exit
#+end_src

And then stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

*** Video
**** Davinci Resolve

🎥 [[https://youtu.be/kXFYmkQo5Dk][Davinci Resolve 21 install on Freebsd with Cuda]]

***** Change directory into the davinci-resolve directory

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/video/davinci-resolve
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Videos directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

Note: The Makefile will create the following empty directories in your video directory.

These are just empty mount points that are required by Davinci Resolve.

#+begin_example
CacheClip
Resolve Project Backups
#+end_example

All the Davinci Resolve are files kept in the storage directory.

***** build

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_USER="${USER}" \
-t localhost/davinci-resolve .
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** Davinci Resolve download

Download the latest version of Davinci Resolve.

[[https://www.blackmagicdesign.com/uk/products/davinciresolve]]

***** Unzip the Davinci Resolve zip file

Create a resolve-zip directory in the your video directory.

#+begin_src sh
mkdir -p ~/video/resolve-zip
#+end_src

Note if you are using a newer version of Davinci Resolve,
change the version number in the commands listed below.

Move the zip file into the resolve directory.

#+begin_src sh
mv DaVinci_Resolve_21.0.1_Linux.zip ~/video/resolve-zip
#+end_src

Change into the resolve directory.

#+begin_src sh
cd ~/video/resolve-zip
#+end_src

Install zip on Freebsd.

#+begin_src sh
doas pkg install zip
#+end_src

Unzip the file.

#+begin_src sh
unzip DaVinci_Resolve_21.0.1_Linux.zip
#+end_src

***** Enter the container

Change directory into the davinci-resolve directory.

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/video/davinci-resolve
#+end_src

Enter the podman container.

#+begin_src sh
doas podman exec -it -u ${USER} davinci-resolve /bin/bash
#+end_src

***** Davinci Resolve install

Inside the Podman container change into the resolve directory you created.

#+begin_src sh
cd Videos/resolve-zip
#+end_src

Extract the DaVinci_Resolve_21.0.1_Linux.run file with --appimage-extract.

#+begin_src sh
./DaVinci_Resolve_21.0.1_Linux.run --appimage-extract
#+end_src

Change directory into the squashfs-root directory.

#+begin_src sh
cd squashfs-root
#+end_src

Copy the directories from the squashfs-root directory into /opt/resolve/

#+begin_src sh
cp -a bin libs share plugins LUT Fusion Developer graphics docs scripts UI_Resource Onboarding Certificates Control CentOSUpdate BlackmagicRAWPlayer BlackmagicRAWSpeedTest "DaVinci Control Panels Setup" "Fairlight Studio Utility" "Technical Documentation" /opt/resolve/
#+end_src

***** Desktop entry

On the Freebsd host.

Copy the DV_Resolve.png from the squashfs-root directory to the default icons directory for the desktop entry.

#+begin_src sh
doas cp ~/video/resolve-zip/squashfs-root/graphics/DV_Resolve.png /usr/local/share/icons/hicolor/scalable/apps
#+end_src

Copy the DaVinciResolve.desktop to the applications directory.

#+begin_src sh
cp ~/podman/freebsd-cuda/base-build/assets/applications/davinci-resolve/DaVinciResolve.desktop ~/.local/share/applications
#+end_src

After you have copied directories in the step above you can delete the following files and directories.

#+begin_src sh
rm DaVinci_Resolve_21.0.1_Linux.run
#+end_src

#+begin_src sh
rm Linux_Installation_Instructions.html
#+end_src

#+begin_src sh
rm -rf squashfs-root
#+end_src

But keep the DaVinci_Resolve_21.0.1_Linux.zip

***** Stop the container

Change into the container directory.

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/video/davinci-resolve
#+end_src

And stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

***** ffmpeg scripts
****** ffmpeg script to convert video to prores

Freebsd ffmpeg script to convert video to prores video pcm audio.

Copy the prores-video script to your bin directory.

#+begin_src sh
cp ~/podman/freebsd-cuda/base-build/assets/scripts/davinci-resolve/prores-video ~/bin
#+end_src

prores-video

#+begin_src sh
#!/bin/sh

#===============================================================================
# convert video to prores pcm
#===============================================================================


#===============================================================================
# script usage
#===============================================================================

usage()
{
# if argument passed to function echo it
[ -z "${1}" ] || echo "! ${1}"
# display help
echo "\
# convert video to prores pcm

$(basename "$0") -i input.mov -o output.mp4
-i infile.mov
-o outfile.mov :optional agument # if option not provided defaults to input-name.mov"
exit 2
}


#===============================================================================
# error messages
#===============================================================================

NOTFILE_ERR='not a file'
INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'


#===============================================================================
# check number of aruments passed to script
#===============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"


#===============================================================================
# getopts check options passed to script
#===============================================================================

while getopts ':i:o:h' opt
do
  case ${opt} in
     i) input="${OPTARG}"
	[ -f "${input}" ] || usage "${input} ${NOTFILE_ERR}";;
     o) output="${OPTARG}";;
     h) usage;;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#===============================================================================
# variables
#===============================================================================

input_nopath="${input##*/}"
input_name="${input_nopath%.*}"

# defaults for variables if not defined
output_default="${input_name}.mov"


#===============================================================================
# functions
#===============================================================================

# prores function
prores () {
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -i "${input}" \
    -c:v prores_ks \
    -profile:v 2 \
    -vendor apl0 \
    -g 1 \
    -pix_fmt yuv422p10le \
    -c:a pcm_s16le \
    -ar 48000 \
    -f mov \
    "${output:=${output_default}}"
}

# run the prores function
prores "${input}"
#+end_src

****** ffmpeg script to convert prores to h265

Freebsd ffmpeg script to convert Prores video to h265.

Copy the h265-nvenc script to your bin directory.

#+begin_src sh
cp ~/podman/freebsd-cuda/base-build/assets/scripts/davinci-resolve/h265-nvenc ~/bin
#+end_src

h265-nvenc

#+begin_src sh
#!/bin/sh

#===============================================================================
# convert video to h265/aac
#===============================================================================


#===============================================================================
# script usage
#===============================================================================

usage()
{
# if argument passed to function echo it
[ -z "${1}" ] || echo "! ${1}"
# display help
echo "\
# convert video to h265/aac

$(basename "$0") -i input.mov -o output.mp4
-i infile.mov
-o outfile.mov :optional agument # if option not provided defaults to input-name.mp4"
exit 2
}


#===============================================================================
# error messages
#===============================================================================

NOTFILE_ERR='not a file'
INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'


#===============================================================================
# check number of aruments passed to script
#===============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"


#===============================================================================
# getopts check options passed to script
#===============================================================================

while getopts ':i:o:h' opt
do
  case ${opt} in
     i) input="${OPTARG}"
	[ -f "${input}" ] || usage "${input} ${NOTFILE_ERR}";;
     o) output="${OPTARG}";;
     h) usage;;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#===============================================================================
# variables
#===============================================================================

input_nopath="${input##*/}"
input_name="${input_nopath%.*}"

# defaults for variables if not defined
output_default="${input_name}.mp4"


#===============================================================================
# functions
#===============================================================================

# h265 function
h265 () {
    nv-sglrun \
    ffmpeg \
    -hide_banner \
    -stats -v panic \
    -i "${input}" \
    -c:v hevc_nvenc \
    -pix_fmt p010le \
    -preset slow \
    -tier high \
    -rc vbr \
    -cq 22 \
    -b:v 0 \
    -maxrate 50M \
    -c:a aac \
    -b:a 320k \
    -ar 48000 \
    "${output:=${output_default}}"
}

# run the h265 function
h265 "${input}"
#+end_src

*** Graphics
**** Blender
***** Change directory into the blender directory

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/graphics/blender
#+end_src

***** Run the Makefile

Run make Makefile which will create the persistent storage directories.

And the .env file which will set your username, id and set the mounted Videos directory.

Make sure to review the .env file to make sure everything is correct.

#+begin_src sh
make
#+end_src

***** build

#+begin_src sh
doas podman build \
--network=host \
--os linux \
--arch amd64 \
--build-arg HOST_USER="${USER}" \
-t localhost/blender .
#+end_src

***** Blender download and install

[[https://www.blender.org/download/]]

Move the blender-5.1.2-linux-x64.tar.xz into the podman blender directory

#+begin_src sh
mv blender-*-linux-x64.tar.xz ~/podman/freebsd-cuda/containers/graphics/blender
#+end_src

Extract the tar file into the blender directory.

#+begin_src sh
tar -xvpf blender-*-linux-x64.tar.xz -C blender --strip-components=1
#+end_src

Remove the blender tar file.

#+begin_src sh
rm blender-*-linux-x64.tar.xz
#+end_src

***** Start the container

#+begin_src sh
doas podman-compose up -d
#+end_src

***** Enter the container

If you need to enter the podman container.

#+begin_src sh
doas podman exec -it -u ${USER} blender /bin/bash
#+end_src

Note its not required to enter the container to get blender working.

***** Desktop entry

On the Freebsd host.

Copy the blender.svg from the blender directory to the default icons directory for the desktop entry.

#+begin_src sh
doas cp ~/podman/freebsd-cuda/containers/graphics/blender/blender/blender.svg /usr/local/share/icons/hicolor/scalable/apps
#+end_src

Copy the blender.desktop to the applications directory.

#+begin_src sh
cp ~/podman/freebsd-cuda/base-build/assets/applications/blender/blender.desktop ~/.local/share/applications
#+end_src

***** Videos directory mounted from Freebsd into the Blender container.

The Makefile will automatically detect the name of your videos directory on Freebsd.

Your videos directory on Freebsd is mounted into the Blender container for file access.

So you store you Blender files on Freebsd in the Videos directory.

***** Stop the container

Change into the container directory.

#+begin_src sh
cd ~/podman/freebsd-cuda/containers/graphics/blender
#+end_src

And stop the container.

#+begin_src sh
doas podman-compose down
#+end_src

*** Custom containers

You can create a custom directory for your own containers.

Which wont be tracked by git,
because i have set that directory to be ignored using gitignore.

#+begin_src sh
mkdir -p ~/podman/freebsd-cuda/containers/custom
#+end_src

Then create the project in the custom directory.

#+begin_src sh
mkdir -p ~/podman/freebsd-cuda/containers/custom/myproject
#+end_src

And copy the Dockerfile, compose.yaml, .env and the Makefile from one of the other projects.

*** Prune old images

#+begin_src sh
doas podman image prune -f
#+end_src

*** Upgrading containers

To upgrade containers remove the old containers and then rebuild them.

**** Delete the davinci-resolve container

#+begin_src sh
doas podman rmi localhost/davinci-resolve:latest
#+end_src

**** Delete the ollama container

#+begin_src sh
doas podman rmi localhost/ollama:latest
#+end_src

**** Delete the firefox container

#+begin_src sh
doas podman rmi localhost/firefox:latest
#+end_src

**** Delete the ffmpeg-scripts container

#+begin_src sh
doas podman rmi localhost/ffmpeg-scripts:latest
#+end_src

**** Delete the demucs container

#+begin_src sh
doas podman rmi localhost/demucs:latest
#+end_src

**** Delete the whisperx container

#+begin_src sh
doas podman rmi localhost/whisperx:latest
#+end_src

**** Delete the kokoro-onnx container

#+begin_src sh
doas podman rmi localhost/kokoro-onnx:latest
#+end_src

**** Delete the comfyui container

#+begin_src sh
doas podman rmi localhost/comfyui:latest
#+end_src

**** Delete the blender container

#+begin_src sh
doas podman rmi localhost/blender:latest
#+end_src

**** Delete the base-image container

#+begin_src sh
doas podman rmi localhost/base-image:latest
#+end_src

** Podman install

There's also a podman-suite meta package that will pull additional packages for you (buildah, skopeo).

To install podman-compose you need to install the py311-podman-compose package as well

#+begin_src sh
doas pkg install podman-suite py311-podman-compose
#+end_src

*** fstab

To properly support Podman's container restart policy, conmon needs fdescfs(5) to be mounted on /dev/fd.

If /dev/fd is not already mounted:

#+begin_src sh
doas mount -t fdescfs fdesc /dev/fd
#+end_src

To make it permanent, add the following line to /etc/fstab:

#+begin_src sh
doas vi /etc/fstab
#+end_src

#+begin_src conf
fdesc   /dev/fd         fdescfs         rw      0       0
#+end_src

#+begin_src sh
doas mount -t procfs proc /proc
#+end_src

*** linux

Enable Linux compatibility at boot

#+begin_src sh
doas sysrc linux_enable="YES"
#+end_src

Start the service and load the 64-bit Linux kernel module

#+begin_src sh
doas service linux start
#+end_src

Load linux 

#+begin_src sh
doas kldload linux64
#+end_src

Ensure it loads every boot

#+begin_src sh
doas sysrc kld_list+="linux64"
#+end_src

*** pf

#+begin_src sh
service pf enable
#+end_src

#+begin_src sh
service pf start
#+end_src

Note fix error

#+begin_src sh
doas sysrc 'pf_load=YES'
#+end_src

#+begin_src sh
kldload pf
#+end_src

Container networking relies on NAT to allow container network packets out to the host's network. This requires a PF firewall to perform the translation. A simple example is included - to use it:

#+begin_src sh
cp /usr/local/etc/containers/pf.conf.sample .
#+end_src

pf.conf.sample

#+begin_src conf
# Change these to the interface(s) with the default route
v4egress_if = "ix0"
v6egress_if = "ix0"

nat on $v4egress_if inet from <cni-nat> to any -> ($v4egress_if)
nat on $v6egress_if inet6 from <cni-nat> to !ff00::/8 -> ($v6egress_if)

rdr-anchor "cni-rdr/*"
nat-anchor "cni-rdr/*"
table <cni-nat>
#+end_src

Edit /etc/pf.conf and set v4egress_if, v6egress_if variables to your network interface(s)s

The sample PF configuration includes support for port redirections. These are implemented as redirect rules in anchors nested under cni-rdr.

Redirect rules will work if the destination address is localhost (e.g. 127.0.0.1 or ::1) - to enable this, the following line must be included in your /etc/pf.conf:

#+begin_src conf
nat-anchor "cni-rdr/*"
#+end_src

#+begin_src sh
doas vi /etc/pf.conf
#+end_src

#+begin_src conf
#=========================================================================#
# pf.conf
#=========================================================================#

#=========================================================================#
# variables, macro and tables                                             #
#=========================================================================#

int_if="lagg0" # lagg0 failover
v4egress_if = "lagg0" # podman
v6egress_if = "lagg0" # podman
vpn_if="tun0" # vpn interface
all_networks="0.0.0.0/0"
vpn_network="$vpn_if:network"
# 6881, 6882 = transmission. , 22000, 22000, 21027 = syncthing
# searxng podman = 8080
tcp_services = "{ ntp, 6881, 22000, 8080 }" # tcp services - torrent
udp_services = "{ ntp, 6882, 22000, 21027 }" # udp services - torrent
#nfs_services = "{ 2049 }" # 2049 = nfs
icmp_types = "{ echoreq, unreach }"
tcp_state="flags S/SA keep state"
udp_state="keep state"

#table <internet> { $all_networks, !self, !$int_if:network } # internet
table <lan> { $int_if:network, !self }                      # lan network
table <myself> { self }                                     # self
table <martians> { 0.0.0.0/8 10.0.0.0/8 127.0.0.0/8 169.254.0.0/16     \
	 	   172.16.0.0/12 192.0.0.0/24 192.0.2.0/24 224.0.0.0/3 \
	 	   192.168.0.0/16 198.18.0.0/15 198.51.100.0/24        \
	 	   203.0.113.0/24 }                         # broken networks

#=========================================================================#
# global policy                                                           #
#=========================================================================#

set block-policy drop
set loginterface $int_if
set fingerprints "/etc/pf.os"
set skip on { lo0, cni-podman0 }
scrub in all fragment reassemble no-df max-mss 1440
# nat jail
nat on $int_if from {lo1:network} to any -> ($int_if)
# podman nat
nat on $v4egress_if inet from <cni-nat> to any -> ($v4egress_if)
nat on $v6egress_if inet6 from <cni-nat> to !ff00::/8 -> ($v6egress_if)
# podman anchor
rdr-anchor "cni-rdr/*"
nat-anchor "cni-rdr/*"
table <cni-nat>
# antispoof
antispoof log quick for { lo $int_if } label "block_spoofing"


#=========================================================================#
# block                                                                   #
#=========================================================================#

block log all # block log all
block return out quick inet6 all tag IPV6 # block ipv6 
block in quick inet6 all tag IPV6 # block ipv6


#=========================================================================#
# anchors                                                                 #
#=========================================================================#

# openvpn - anchor
anchor "openvpn"

#=========================================================================#
# traffic tag                                                             #
#=========================================================================#

# icmp
pass inet proto icmp all icmp-type $icmp_types keep state tag ICMP

# Allow the tcp and udp services defined in the macros at the top of the file
pass in on $int_if inet proto tcp from any to ($int_if) port $tcp_services $tcp_state tag TCP_IN
pass in on $int_if inet proto udp from any to ($int_if) port $udp_services $udp_state tag UDP_IN

# outbound traffic
block out on $int_if all
pass out quick on $int_if all modulate state
#+end_src

restart pf

#+begin_src sh
doas service pf restart
#+end_src

*** zfs

create a zfs dataset for podman

#+begin_src sh
doas zfs create -o mountpoint=/var/db/containers zroot/containers
#+end_src

*** sysctl

apply net.pf.filter_local=1

#+begin_src sh
doas sysctl net.pf.filter_local=1
#+end_src

set net.pf.filter_local=1 permanently

#+begin_src sh
doas vi /etc/sysctl.conf
#+end_src

#+begin_src conf
#=========================================================================#
# podman
#=========================================================================#

net.pf.filter_local=1
#+end_src

*** podman enable

Podman can restart containers after a host is rebooted. To enable this, use:

#+begin_src sh
doas sysrc podman_enable=YES
#+end_src

or you can manually edit your /etc/rc.conf

#+begin_src sh
doas vi /etc/rc.conf
#+end_src

#+begin_src conf
#=========================================================================#
# podman
#=========================================================================#

podman_enable=YES
#+end_src

*** registries.conf

edit the registries.conf to define repos to podman

#+begin_src sh
doas vi /usr/local/etc/containers/registries.conf
#+end_src

append the following code

#+begin_src conf
unqualified-search-registries = ["docker.io", "quay.io", "ghcr.io"]

[[registry]]
location = "docker.io"

[[registry]]
location = "quay.io"

[[registry]]
location = "ghcr.io"
#+end_src

*** podman zfs dataset for config files

Its good practice to create a zfs dataset for the podman directory

note: change djwilcox to your username in the examples below

we will also create a zfs dataset for our podman config files

#+begin_src sh
doas zfs create zroot/home/djwilcox/podman
#+end_src

change the permissions

#+begin_src sh
doas chown -R djwilcox:djwilcox /home/djwilcox/podman
#+end_src

if you dont want to create a zfs dataset

you can just create a directory

#+begin_src sh
mkdir -p ~/podman
#+end_src

*** doas podman set up

set up doas so you can can run podman without being prompted for a password

#+begin_src sh
doas vi 
#+end_src

change username to your username

#+begin_src conf
#=========================================================================#
# doas.conf
#=========================================================================#

#=========================================================================#
# permit user
#=========================================================================#

permit keepenv setenv { PATH } username


#=========================================================================#
# allow root to switch to our user
#=========================================================================#

permit nopass keepenv setenv { PATH } root as username


#=========================================================================#
# permit user - no pass
#=========================================================================#

permit nopass keepenv setenv { PATH } username


#=========================================================================#
# podman permit user - no pass
#=========================================================================#

permit nopass keepenv username cmd /usr/local/bin/podman


#=========================================================================#
# root as root
#=========================================================================#

permit nopass keepenv root as root
#+end_src

*** devfs.rules

Add the localrules to your rc.conf with syscr

#+begin_src sh
doas sysrc devfs_system_ruleset="localrules"
#+end_src

Or you can manually edit your rc.conf

#+begin_src sh
doas vi /etc/rc.conf
#+end_src

add the following code

#+begin_src conf
devfs_system_ruleset="localrules"
#+end_src

Note: add devfs rules to config

Edit your devfs.rules

#+begin_src sh
doas vi /etc/devfs.rules
#+end_src

Add the following code

#+begin_src conf
[localrules=5]
add path 'da*' mode 0660 group operator
add path 'dri/*' mode 0660 group video
add path 'drm/*' mode 0660 group video
add path 'input/*' mode 0660 group video
add path 'input/event*' mode 0660 group video
add path 'nvidia*' mode 0660 group video

[devfsrules_jail=4]
add include $devfsrules_unhide_basic
add include $devfsrules_unhide_login
add path 'mixer*' unhide
add path 'dsp*' unhide
add path 'dri*' unhide
add path 'drm*' unhide
add path 'nvidia*' unhide
add path 'speaker*' unhide
#+end_src

*** podman test

run the hello workd podmand container

#+begin_src sh
doas podman run --rm docker.io/dougrabson/hello
#+end_src

